### ISSUE TITLE
Error doing `docker pull ncbi/pgap:2018-07-05.build2884`

### ISSUE THREAD

**Issue by mhsieh** [ncbi-gpipe/pgap#1]
Hi,
    I got an error running `./wf_pgap_simple.cwl mg37_input.yaml` trying out the new distribution:
```
Pulling repository ncbi/pgap
FATA[0185] Repository not found
Workflow or tool uses unsupported feature:
Docker is required to run this tool: Command '['docker', 'pull', 'ncbi/pgap:2018-07-05.build2884']' returned non-zero exit status 1.
```

Is there something I can do to fix it?
Thanks,
--mj

**Comment by slottad** [comment]
Have you installed Docker, and tested that you can run it? You'll need to follow the instructions at https://docs.docker.com/install/ and test to see if you can actually run it with 

```shell
~$ docker run hello-world
Hello from Docker!
This message shows that your installation appears to be working correctly.
```

**Comment by mhsieh** [comment]
```
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from hello-world

b6d845cb453c: Pull complete 
3535063d9957: Pull complete 
Digest: sha256:135a30bd414bd8d23e386763e36f3dc4ee8ed25d2d6068082c0af796513d9d0d
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/
```

**Comment by mhsieh** [comment]
Here is my log on the example: https://gist.github.com/mhsieh/70e7a2bda0cfd15e96a2975afe55a2ad

**Comment by mhsieh** [comment]
docker pull log - https://gist.github.com/mhsieh/08055ba254c250f59a21b0c4742c07be

**Comment by slottad** [comment]
Sorry, I inadvertently hit the wrong button and closed this issue. Oops.

It looks like the docker pull command didn't complete successfully. That can happen with large images like this. Try doing the pull manually:

```shell
~$ docker pull ncbi/pgap:2018-07-05.build2884
```
Once this is successful, The pipeline will not need to do it again.

**Comment by mhsieh** [comment]
Thanks Douglas, that essentially was what I did at https://gist.github.com/mhsieh/08055ba254c250f59a21b0c4742c07be

Now you mentioned the size of the image, let me try several times more and see if I can get it through.

**Comment by mhsieh** [comment]
Okay I finally was able to download the image after several retries. I can now proceed to run the examples. Thanks!

**Comment by slottad** [comment]
Cool. We know the container size is an issue, and it is one of the things we will be working on.
